function b = fir8(symbolrate)
%FIR_450K_220HZ_8800HZ_104N 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 07-Aug-2022 16:46:11

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = symbolrate;  % Sampling Frequency

Fpass = 174;             % Passband Frequency
Fstop = 1/2*Fs*0.038+Fpass;            % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
% Hd = dfilt.dffir(b);

% [EOF]
